Administration:
- changed-files:
  - any-glob-to-any-file: admin/**

Code:
- changed-files:
  - any-glob-to-any-file: code/**

Code Maintenance:
- changed-files:
  - any-glob-to-any-file:
    - controllers/**
    - _DEFINES/**
    - _HELPERS/**

Sound:
- changed-files: 
  - any-glob-to-any-file: sound/**

Sprite:
- changed-files:
  - any-glob-to-any-file: icons/**

Mapping:
- changed-files:
  - any-glob-to-any-file: _maps/**

Documentation:
- changed-files:
  - any-glob-to-any-file:
    - .github/**
    - README.md**

Balance:
- changed-files:
  - any-glob-to-any-file:
    - code/modules/jobs/job_types/roguetown/**
